<?php
	
	/**
	 
	 Welcome page, as generated by iWeb and one lazy coder.
	 
	 **/
	
	?>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="Generator" content="iWeb 3.0.3" />
<meta name="iWeb-Build" content="local-build-20110531" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<meta name="viewport" content="width=700" />
<title>SecretKey</title>
<link rel="stylesheet" type="text/css" media="screen,print" href="Keys_for_the_Cloud_files/Keys_for_the_Cloud.css" />
<!--[if lt IE 8]><link rel='stylesheet' type='text/css' media='screen,print' href='Keys_for_the_Cloud_files/Keys_for_the_CloudIE.css'/><![endif]-->
<!--[if gte IE 8]><link rel='stylesheet' type='text/css' media='screen,print' href='Media/IE8.css'/><![endif]-->
<script type="text/javascript" src="Scripts/iWebSite.js"></script>
<script type="text/javascript" src="Scripts/Widgets/SharedResources/WidgetCommon.js"></script>
<script type="text/javascript" src="Scripts/Widgets/Navbar/navbar.js"></script>
<script type="text/javascript" src="Keys_for_the_Cloud_files/Keys_for_the_Cloud.js"></script>
</head>
<body style="background: rgb(25, 21, 21); margin: 0pt; " onload="onPageLoad();" onunload="onPageUnload();">
<div style="text-align: center; ">
<div style="margin-bottom: 0px; margin-left: auto; margin-right: auto; margin-top: 0px; overflow: hidden; position: relative; word-wrap: break-word;  text-align: left; width: 700px; " id="body_content">
<div style="background: transparent url(Keys_for_the_Cloud_files/rp_tile_v6.jpg) repeat scroll top left; width: 700px; ">
<div style="height: 97px; margin-left: 0px; position: relative; width: 700px; z-index: 10; " id="header_layer">
<div style="height: 0px; line-height: 0px; " class="bumper"> </div>
<div style="height: 95px; width: 634px;  height: 95px; left: 33px; position: absolute; top: 2px; width: 634px; z-index: 1; " class="tinyText">
<div style="position: relative; width: 634px; ">
<img src="Keys_for_the_Cloud_files/shapeimage_1.png" alt="SecretKey" style="height: 55px; left: 0px; margin-left: 1px; margin-top: 24px; position: absolute; top: 0px; width: 249px; " />
</div>
</div>
</div>
<div style="margin-left: 0px; position: relative; width: 700px; z-index: 0; " id="nav_layer">
<div style="height: 0px; line-height: 0px; " class="bumper"> </div>
<div style="height: 490px; width: 700px;  height: 490px; left: 0px; position: absolute; top: -489px; width: 700px; z-index: 1; " class="tinyText style_SkipStroke">
<img src="Keys_for_the_Cloud_files/navfill-v2.jpg" alt="" style="border: none; height: 490px; width: 700px; " />
</div>
<div style="height: 1px; line-height: 1px; " class="tinyText"> </div>
<div class="com-apple-iweb-widget-navbar flowDefining" id="widget0" style="margin-left: 0px; margin-top: -1px; opacity: 1.00; position: relative; width: 700px; z-index: 1; ">

<div id="widget0-navbar" class="navbar">


<div id="widget0-bg" class="navbar-bg">


<ul id="widget0-navbar-list" class="navbar-list">
<li></li> 
</ul>


</div>


</div>
</div>
<script type="text/javascript"><!--//--><![CDATA[//><!--
new NavBar('widget0', 'Scripts/Widgets/Navbar', 'Scripts/Widgets/SharedResources', '.', {"path-to-root": "", "navbar-css": ".navbar {\n\tfont-family: 'Courier New', Courier, monospace, serif;\n\tfont-size: 1.1em;\n\tcolor: #AFAA9F;\n\tmargin: -2px 0 0 0px;\n\tline-height: 20px;\n\tpadding: 5px 0 12px 0;\n\tfont-weight: bold;\n\tbackground-image: url(Keys_for_the_Cloud_files\/navfill-v2_1.jpg);\n}\n\n.navbar-bg {\n\ttext-align: left;\n}\n\n.navbar-bg ul {\n\tlist-style: none;\n\tmargin: 0px;\n\tpadding: 0 10px 0 30px;\n}\n\n\nli {\n\tlist-style-type: none;\n\tdisplay: inline;\n\tpadding: 0px 25px 0 0;\n}\n\n\nli a {\n\ttext-decoration: none;\n\tcolor: #AFAA9F;\n}\n\nli a:visited {\n\ttext-decoration: none;\n\tcolor: #AFAA9F;\n}\n\nli a:hover\n{\n \tcolor: #D64600;\n}\n\n\nli.current-page a\n{\n\t color: #fff;\n\n}\n", "current-page-GUID": "C456F067-E933-4B8A-A07C-40CF852A5506", "isCollectionPage": "NO"});
	//--><!]]></script>
<div style="clear: both; height: 0px; line-height: 0px; " class="spacer"> </div>
</div>
<div style="margin-left: 0px; position: relative; width: 700px; z-index: 5; " id="body_layer">
<div style="height: 0px; line-height: 0px; " class="bumper"> </div>
<div style="height: 25px; width: 700px;  height: 25px; left: 0px; position: absolute; top: -15px; width: 700px; z-index: 1; " class="tinyText style_SkipStroke_1">
<img src="Keys_for_the_Cloud_files/pagetop10.png" alt="" style="border: none; height: 25px; width: 700px; " />
</div>



<div style="height: 52px; width: 634px;  height: 52px; left: 33px; position: absolute; top: 23px; width: 634px; z-index: 1; " class="tinyText style_SkipStrokeSkipFillSkipOpacity">
<div style="position: relative; width: 634px; ">
<img src="Keys_for_the_Cloud_files/shapeimage_2.png" alt="WTF" style="height: 27px; left: 0px; margin-left: 4px; margin-top: 13px; position: absolute; top: 0px; width: 50px; " />
</div>
</div>



<div style="height: 52px; width: 634px;  height: 52px; left: 33px; position: absolute; top: 505px; width: 634px; z-index: 1; " class="tinyText style_SkipStrokeSkipFillSkipOpacity">
<div style="position: relative; width: 634px; ">
<img src="Keys_for_the_Cloud_files/shapeimage_3.png" alt="USAGE" style="height: 28px; left: 0px; margin-left: 5px; margin-top: 12px; position: absolute; top: 0px; width: 74px; " />
</div>
</div>



<div id="id1" style="height: 91px; left: 35px; position: absolute; top: 65px; width: 648px; z-index: 1; " class="style_SkipStroke_2 shape-with-text">
<div class="text-content graphic_textbox_layout_style_default_External_648_91" style="padding: 0px; ">
<div class="graphic_textbox_layout_style_default">
<p style="padding-bottom: 0pt; padding-top: 0pt; " class="Body">With “the cloud” becoming main-stream encryption must follow. One of the puzzles I’ve been wondering how to solve has been how to deal with private keys in the cloud, the bottom line is once your private key is compromised so is the encryption, this has lead me to a thought.... what if multiple pwnz were required to get at the oh-so precious key?</p>
</div>
</div>
</div>



<div style="height: 52px; width: 634px;  height: 52px; left: 34px; position: absolute; top: 157px; width: 634px; z-index: 1; " class="tinyText style_SkipStrokeSkipFillSkipOpacity">
<div style="position: relative; width: 634px; ">
<img src="Keys_for_the_Cloud_files/shapeimage_4.png" alt="The theory" style="height: 28px; left: 0px; margin-left: 3px; margin-top: 12px; position: absolute; top: 0px; width: 138px; " />
</div>
</div>



<div id="id2" style="height: 321px; left: 35px; position: absolute; top: 204px; width: 648px; z-index: 1; " class="style_SkipStroke_2 shape-with-text">
<div class="text-content graphic_textbox_layout_style_default_External_648_321" style="padding: 0px; ">
<div class="graphic_textbox_layout_style_default">
<p style="padding-top: 0pt; " class="Body">In a traditional system we have the encryption algorithm and the key. <br /></p>
<p class="Body"><br /></p>
<p class="Body">With symmetric encryption, for example a file “secured” by a password the same key is used to open and lock the data, in a cloud based app the key has to stored somewhere where the system can accesses it else it cannot access the data.  Asymmetric systems suffer a similar yet different fault, the data may be encrypted with a different key to which it is decrypted but the decryption key still needs to reside somewhere accessible to the cloud. <br /></p>
<p class="Body"><br /></p>
<p class="Body">Whatever the encryption we have two parties the encrypted data and the key the hackers are after... like it or not in many cases both reside in the same place! (dropbox anyone?)<br /></p>
<p class="Body"><br /></p>
<p class="Body">This is where secretkey comes in, the idea is to create a third party responsible to issuing the key to decrypt the data;  an attacker must gain access to the encrypted data and be able to generate the correct request to get the key issued (how hard that is will ultimately depend on the attack) <br /></p>
</div>
</div>
</div>



<div id="id3" style="height: 389px; left: 35px; position: absolute; top: 551px; width: 648px; z-index: 1; " class="style_SkipStroke_2 shape-with-text">
<div class="text-content graphic_textbox_layout_style_default_External_648_389" style="padding: 0px; ">
<div class="graphic_textbox_layout_style_default">
<p style="padding-top: 0pt; " class="Body">Basic usage is as follows:<br /></p>
<p class="Body"><br /></p>
<p class="Body"> <span class="style">$curl </span><a title="http://secretkey-linickx.rhcloud.com/?k=mykey" href="http://secretkey-linickx.rhcloud.com/?k=mykey" class="style">http://secretkey-linickx.rhcloud.com/?k=mykey</a><span class="style"><br /></span></p>
<p class="Body"><span class="style">1a68152d25ffc9d5ec8be0c6cfe718b44579c58fb37ff569fd9eab8419c77e0a <br /></span></p>
<p class="Body"><span class="style"> $</span><br /></p>
<p class="Body"><br /></p>
<p class="Body">I have made a HTTP request with an option “k=mykey”. The “k” is the client secret. The result is a long key that can be used as a secret key for encryption purposes.<br /></p>
<p class="Body"><br /></p>
<p class="Body">Now the resulting secret is generated from a combination of the client secret a provider secret (i.e. one saved on secretkey) and properties of the request. The IP address of the client is used to generate the ket, this is not good for DHCP scenarios therefore dhcp=1 can be sent to generate the same key no matter the client ip:<br /></p>
<p class="Body"><br /></p>
<p class="paragraph_style">$curl &quot;<a title="http://secretkey-linickx.rhcloud.com/?k=mykey&amp;dhcp=1" href="http://secretkey-linickx.rhcloud.com/?k=mykey&amp;dhcp=1">http://secretkey-linickx.rhcloud.com/?k=mykey&amp;dhcp=1</a>&quot;<br /></p>
<p class="paragraph_style">927f8f98c100d99af33b4763528c24291c07bcd230f1d9245b0788fa2ac2b5ed<br /></p>
<p class="paragraph_style">$<br /></p>
<p class="Body"><br /></p>
</div>
</div>
</div>



<div style="height: 52px; width: 634px;  height: 52px; left: 33px; position: absolute; top: 895px; width: 634px; z-index: 1; " class="tinyText style_SkipStrokeSkipFillSkipOpacity">
<div style="position: relative; width: 634px; ">
<img src="Keys_for_the_Cloud_files/shapeimage_5.png" alt="Get involved" style="height: 28px; left: 0px; margin-left: 5px; margin-top: 12px; position: absolute; top: 0px; width: 159px; " />
</div>
</div>



<div style="height: 52px; width: 634px;  height: 52px; left: 33px; position: absolute; top: 1006px; width: 634px; z-index: 1; " class="tinyText style_SkipStrokeSkipFillSkipOpacity">
<div style="position: relative; width: 634px; ">
<img src="Keys_for_the_Cloud_files/shapeimage_6.png" alt="DinGbaT Alert!" style="height: 28px; left: 0px; margin-left: 5px; margin-top: 12px; position: absolute; top: 0px; width: 184px; " />
</div>
</div>



<div id="id4" style="height: 63px; left: 35px; position: absolute; top: 942px; width: 648px; z-index: 1; " class="style_SkipStroke_2 shape-with-text">
<div class="text-content graphic_textbox_layout_style_default_External_648_63" style="padding: 0px; ">
<div class="graphic_textbox_layout_style_default">
<p style="padding-bottom: 0pt; padding-top: 0pt; " class="Body">The sourcecode for this idea will be posted on <a title="https://github.com/linickx/secretkey" href="https://github.com/linickx/secretkey">https://github.com/linickx/secretkey</a>  take a look, don’t just critise on how easy it is to crack, make a suggestion!</p>
</div>
</div>
</div>
<div style="height: 1058px; line-height: 1058px; " class="spacer"> </div>
</div>
<div style="height: 150px; margin-left: 0px; position: relative; width: 700px; z-index: 15; " id="footer_layer">
<div style="height: 0px; line-height: 0px; " class="bumper"> </div>
<div id="id5" style="height: 154px; left: 35px; position: absolute; top: -4px; width: 648px; z-index: 1; " class="style_SkipStroke_2 shape-with-text">
<div class="text-content graphic_textbox_layout_style_default_External_648_154" style="padding: 0px; ">
<div class="graphic_textbox_layout_style_default">
<p style="padding-top: 0pt; " class="Body">The rhcloud server given in the example should not be used for production systems, you should have noticed that it is NOT secured by SSL, this means that anyone with a sniffer can snoop the client secret.<br /></p>
<p class="Body"><br /></p>
<p class="Body">The idea is for you to take the source, add your own provider key and host from a private ssl server that way your client apps can get keys from a trusted 3rd party source ;)<br /></p>
<p class="Body"><br /></p>
<p style="padding-bottom: 0pt; " class="Body"><a title="http://www.linickx.com" href="http://www.linickx.com">© Nick Bettison</a></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>


